[alias]
build-wasm = "build --no-default-features --features wasm --target wasm32-unknown-unknown"
build-wasm-release = "build --release --no-default-features --features wasm --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/release/emval.wasm --out-dir js --target web"